[lib]
crate-type = ["cdylib", "rlib"]

[package]
description = "Shared o-sfu bundle and signaling protocol types"
name = "o-sfu-protocol"

authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version = "1.93"
version.workspace = true

[dependencies]
o-sfu-model.workspace = true
o-sfu-rfc.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"

[lints]
workspace = true
