[package]
description = "o-sfu media core"
name = "o-sfu-core"

authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
internal-benchmarks = []
testing-transport = ["o-sfu-router/test-support"]
worker-benchmarks = ["internal-benchmarks"]

[dependencies]
bitflags = "2.6"
futures-util.workspace = true
itertools = "0.15"
o-sfu-rfc.workspace = true
o-sfu-model.workspace = true
o-sfu-router.workspace = true
o-sfu-telemetry.workspace = true
serde.workspace = true
serde_json.workspace = true
str0m.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uuid = { version = "1.18", features = ["v4"] }
secrecy = { version = "0.10.3", features = ["serde"] }

[target.'cfg(target_os = "linux")'.dependencies]
tokio-uring = "0.5"

[lints]
workspace = true

[dev-dependencies]
o-sfu-telemetry = { workspace = true, features = ["test-support"] }
o-sfu-router = { workspace = true, features = ["test-support"] }
tokio = { workspace = true, features = ["test-util"] }
tracing-subscriber = { version = "0.3", features = ["json"] }
